-- 0001_initial_schema.sql

-- Profiles Table: Stores user information
CREATE TABLE public.profiles (
    id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    full_name text,
    role text DEFAULT 'Team Member'::text,
    team text,
    created_at timestamptz DEFAULT now(),
    PRIMARY KEY (id)
);

-- PWS Tasks Table: Stores PWS line items
CREATE TABLE public.pws_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name text NOT NULL,
    pws_line_item text NOT NULL,
    start_date date,
    due_date date,
    assigned_to uuid REFERENCES public.profiles(id),
    created_at timestamptz DEFAULT now()
);

-- Updates Table: Stores task status updates
CREATE TABLE public.updates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES public.pws_tasks(id),
    user_id uuid NOT NULL REFERENCES public.profiles(id),
    narrative text,
    percent_complete integer,
    blockers text,
    short_status text,
    status text DEFAULT 'draft'::text,
    created_at timestamptz DEFAULT now(),
    submitted_at timestamptz
);

-- Approvals Table: Stores approval history
CREATE TABLE public.approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id bigint NOT NULL REFERENCES public.updates(id),
    approver_id uuid NOT NULL REFERENCES public.profiles(id),
    status text NOT NULL, -- 'approved', 'rejected', 'modified'
    comments text,
    created_at timestamptz DEFAULT now()
);

-- Account Requests Table: Stores new account requests
CREATE TABLE public.account_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    reason text,
    status text DEFAULT 'pending'::text, -- 'pending', 'approved', 'rejected'
    created_at timestamptz DEFAULT now()
);
